In [2]:

import numpy as np
import open3d as o3d
import sys
import os

project_path = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_path not in sys.path:
    sys.path.append(project_path)

from src.preprocessamento.service.preprocessamento_service import PreprocessamentoService
from src.preprocessamento.models.image_model import ImageData
from src.deteccaopontos.deteccao_pontos import DeteccaoPontos
from src.sfm import reconstrucao_sfm

# Parâmetros da câmera (SIMPLE_RADIAL)
K = np.array([
    [2559.68, 0, 1536],
    [0, 2559.68, 1152],
    [0, 0, 1]
], dtype=np.float32)
dist = np.array([-0.0204997, 0, 0, 0, 0], dtype=np.float32)

img1_path = "/home/kaiooliveira/Documentos/kaio/dev/Faculdade/Fotogrametria/fotogrametria_aplicada/resources/input/brute-images/south-building/images/P1180142.JPG"
img2_path = "/home/kaiooliveira/Documentos/kaio/dev/Faculdade/Fotogrametria/fotogrametria_aplicada/resources/input/brute-images/south-building/images/P1180143.JPG"

image_data1 = ImageData(path=img1_path, matriz_intrinseca=K, coeficiente_distorcao=dist)
image_data2 = ImageData(path=img2_path, matriz_intrinseca=K, coeficiente_distorcao=dist)

img1 = PreprocessamentoService(image_data1).get_imagem_corrigida();
img2 = PreprocessamentoService(image_data2).get_imagem_corrigida();


deteccao_pontos_1 = DeteccaoPontos(img1.imagem_processada, metodo="SIFT")
deteccao_pontos_2 = DeteccaoPontos(img2.imagem_processada, metodo="SIFT")

kp1, desc1 = deteccao_pontos_1.detectar_pontos()
kp2, desc2 = deteccao_pontos_2.detectar_pontos()
matches = DeteccaoPontos.corresponder_descritores(desc1, desc2, metodo="BF")

pontos_3d, R, t, _ = reconstrucao_sfm.estimar_poses_e_triangulacao(kp1, kp2, matches, K)

print(f"[INFO] Pontos triangulados: {pontos_3d.shape[0]}")
print(f"[INFO] Matriz de rotação:\n{R}")
print(f"[INFO] Vetor de translação:\n{t.ravel()}")


def mostrar_nuvem_pontos(pontos):
    pc = o3d.geometry.PointCloud()
    pc.points = o3d.utility.Vector3dVector(pontos)
    pc.paint_uniform_color([0.1, 0.6, 0.1])
    o3d.visualization.draw_geometries([pc])

mostrar_nuvem_pontos(pontos_3d)

Total de matches: 1794
Válidos: 457470
Shape proj1: (3, 4)
Shape proj2: (3, 4)
Shape pts1_valid: (2, 1794)
Shape pts2_valid: (2, 1794)
[INFO] Pontos triangulados: 1794
[INFO] Matriz de rotação:
[[ 0.98283907  0.18188483  0.03074519]
 [-0.17938498  0.90355727  0.38910833]
 [ 0.04299286 -0.3879461   0.92067879]]
[INFO] Vetor de translação:
[-0.11161873 -0.96632637  0.23185038]
